### ISSUE TITLE
field_separator, command_separator, escape_separator problem

### ISSUE THREAD

**Issue by joshuakaleb0424** [harmsm/PyCmdMessenger#27]
Hi. I am returning encrypted data from arduino. However the data at times contains some of the separators. Can i turn the separators off? How can i achieve this.

**Comment by harmsm** [comment]
Just got to this and saw you closed it.  Did you figure it out?  The separators are required, but should be escaped automatically by the CmdMessenger and PyCmdMessenger libraries.

**Comment by joshuakaleb0424** [comment]
Yah. I though cmdmessenger was not escaping my data because the string I received is truncated. I was sending the wrong string lol.

**Comment by harmsm** [comment]
Know how that goes. Glad it's working now.
